#!/usr/bin/env python3
"""
Create a master index CSV of all songs from scheduled playlists,
organized by day of week and time block.
"""

import csv

# Define the schedule order and track data
schedule_data = [
    # MONDAY
    {
        'day': 'Monday',
        'time': '9:00 – 10:30am',
        'name': 'The Awakening',
        'tracks': [
            ('Gone Clear', 'William Tyler', '6:08'),
            ('Threnody', 'Goldmund', '4:41'),
            ('Space 1', 'Nala Sinephro', '4:08'),
            ('First Light - Remastered 2004', 'Harold Budd, Brian Eno', '7:07'),
            ('Rose Petals', 'S. Carey', '3:34'),
            ('Hijos Del Sol', 'Hermanos Gutiérrez', '2:57'),
            ('Sunshowers', 'Yasmin Williams', '4:15'),
            ('First Flight', 'Kaitlyn Aurelia Smith', '4:38'),
            ('Rivers That You Cannot See', 'North Americans', '3:55'),
            ('Kenaston', 'Chilly Gonzales', '3:05'),
            ('Perpetuum Mobile', 'Penguin Cafe Orchestra', '4:30'),
            ('Town & Country', 'Bibio', '4:03'),
            ('Iguazu - 2024 Remaster', 'Gustavo Santaolalla', '4:49'),
            ('Sweet Things', 'Mocky', '3:06'),
            ('Salaman', 'Toumani Diabaté, Ballaké Sissoko', '6:14'),
            ('Night After Sidewalk', 'Kaki King', '3:31'),
            ('Holocene', 'Vitamin String Quartet', '5:34'),
            ('Settler', 'Balmorhea', '6:39'),
            ('Glass', 'Hania Rani', '4:31'),
            ("I'm Dragging a Dead Deer Up a Hill", 'Grouper', '2:22'),
            ('Requiem for Dying Mothers, Pt. 2', 'Stars Of The Lid', '7:37'),
            ('The Piano Drop', 'Tim Hecker', '2:54'),
        ]
    },
    {
        'day': 'Monday',
        'time': '10:30am – Noon',
        'name': 'The Forest Path',
        'tracks': [
            ('Carrion Suite', 'Andrew Bird', '9:40'),
            ('Sun Rays Like Stilts', 'Tommy Guerrero', '2:08'),
            ('A Calf Born In Winter', 'Khruangbin', '3:29'),
            ('Two Thousand and Seventeen', 'Four Tet', '4:12'),
            ('Lionheart', 'Emancipator', '4:53'),
            ('A Walk', 'Tycho', '5:17'),
            ('Pacific Theme', 'Broken Social Scene', '5:09'),
            ('The Palm Sunday Tornado Hits Crystal Lake', 'Sufjan Stevens', '1:39'),
            ('Near Light', 'Ólafur Arnalds', '3:29'),
            ('Crosses', 'José González', '2:43'),
            ('Says', 'Nils Frahm', '8:18'),
            ('Looped', 'Kiasmos', '6:01'),
            ('Curious', 'Hauschka', '3:31'),
            ('On the Nature of Daylight', 'Max Richter, Louisa Fuller, Natalia Bonner, John Metcalfe, Philip Sheppard, Chris Worsey', '6:12'),
            ('Indian Summer', 'Jónsi, Alex Somers', '9:01'),
            ('re:member', 'Ólafur Arnalds', '6:05'),
            ('Parce Mihi Domine', 'Jan Garbarek, Cristobal de Morales, The Hilliard Ensemble', '6:42'),
            ('All Melody', 'Nils Frahm', '9:31'),
            ('Yellow is the Colour', 'Bugge Wesseltoft', '10:40'),
            ('Flight from the City', 'Jóhann Jóhannsson, Yuki Numata Resnick, Tarn Travers, Ben Russell, Clarice Jensen', '6:31'),
            ('Ligotage', 'Nils Petter Molvær', '6:44'),
            ('Elevation', 'Hildur Guðnadóttir', '5:58'),
            ('Halving The Compass', 'Helios', '5:27'),
            ('Seoul', 'amiina', '6:57'),
            ('Green Green Grass Of Tunnel', 'múm', '4:51'),
        ]
    },
    {
        'day': 'Monday',
        'time': 'Noon – 2:00pm',
        'name': 'The Village Green',
        'tracks': [
            ('Misread', 'Kings of Convenience', '3:08'),
            ('Mushaboom', 'Feist', '3:45'),
            ('Rebel Rebel', 'Seu Jorge', '2:45'),
            ('Cape Cod Kwassa Kwassa', 'Vampire Weekend', '3:35'),
            ('Diamonds on the Soles of Her Shoes', 'Paul Simon', '5:51'),
            ('If I Ever Feel Better', 'Phoenix', '4:27'),
            ('Chan Chan', 'Buena Vista Social Club', '4:19'),
            ('Sabali', 'Amadou & Mariam', '3:17'),
            ('The Coffee Cola Song', 'Francis Bebey', '5:05'),
            ('The Moss', 'Cosmo Sheldrake', '4:03'),
            ('Young Folks', 'Peter Bjorn and John', '4:37'),
            ('A Minha Menina', 'Os Mutantes', '4:45'),
            ('Ghostwriter', 'RJD2', '5:18'),
            ('Lazy Line Painter Jane', 'Belle and Sebastian', '5:50'),
            ('Fake Palindromes', 'Andrew Bird', '2:53'),
            ('Nantes', 'Beirut', '3:50'),
            ('Cler Achel', 'Tinariwen', '4:28'),
            ('Give Me a Reason', 'Ibibio Sound Machine', '4:18'),
            ('New Slang', 'The Shins', '3:51'),
            ('Wraith Pinned to the Mist and Other Games', 'of Montreal', '4:16'),
            ('Heart It Races', 'Architecture In Helsinki', '3:15'),
            ('Always Like This', 'Bombay Bicycle Club', '4:06'),
            ('Blessa', 'Toro y Moi', '2:43'),
            ('Take My Pain Away', 'Moullinex', '4:38'),
            ('Modern Drift', 'Efterklang', '4:54'),
            ('Azamane Tiliade', 'Bombino', '4:07'),
            ('You Make Me Feel Good - Original Mix', 'Satin Jackets', '7:08'),
            ('Default', 'Django Django', '3:06'),
        ]
    },
    {
        'day': 'Monday',
        'time': '2:00 – 5:00pm',
        'name': 'The Long Drive',
        'tracks': [
            ('My Only Swerving', 'El Ten Eleven', '5:15'),
            ('Lovely Allen', 'Holy Fuck', '4:31'),
            ('Hallogallo', 'NEU!', '10:07'),
            ('Diagonals', 'Stereolab', '5:15'),
            ('Odessa', 'Caribou', '5:16'),
            ('Couleurs', 'M83', '8:37'),
            ('Eple', 'Röyksopp', '3:38'),
            ('The Only Moment We Were Alone - Remastered', 'Explosions In The Sky', '10:01'),
            ('Inspector Norse', 'Todd Terje', '6:41'),
            ("Love On A Real Train - From 'Risky Business' Original Motion Picture Soundtrack", 'Tangerine Dream', '3:59'),
            ('The Haunting Idle', 'The War On Drugs', '3:08'),
            ('Vitamin C - 2004 Remastered Version', 'CAN', '3:34'),
            ('Hollywood', 'Cluster', '4:46'),
            ('Watussi', 'Harmonia', '5:59'),
            ('Open Eye Signal - Remaster 2023', 'Jon Hopkins', '7:49'),
            ('Bad Kingdom', 'Moderat', '4:23'),
            ('Goodbye - 2019 remaster', 'Ulrich Schnauss', '7:54'),
            ('Mogwai Fear Satan', 'Mogwai', '16:20'),
            ('Pop 4', 'GAS', '9:51'),
            ('Autobahn', 'Kraftwerk', '14:27'),
            ('Cha Cha 2000', 'La Düsseldorf', '20:02'),
            ('Sun', 'Caribou', '5:45'),
            ('Dayvan Cowboy', 'Boards of Canada', '5:00'),
            ('Arcadia', 'Apparat', '5:10'),
            ('Articulation', 'Rival Consoles', '6:31'),
            ('Glósóli', 'Sigur Rós', '6:16'),
            ('All Is Violent, All Is Bright', 'God Is An Astronaut', '4:11'),
            ('Alison', 'Slowdive', '3:51'),
            ('Awash', 'Manual', '5:39'),
            ('From Here We Go Sublime', 'The Field', '4:10'),
            ('Silhouettes (I, II & III)', 'Floating Points', '10:43'),
            ('Yatton', 'Beak>', '5:20'),
            ('No Drums', 'Tim Hecker', '3:24'),
        ]
    },
    # TUESDAY
    {
        'day': 'Tuesday',
        'time': '9:00 – 10:30am',
        'name': 'The Observatory',
        'tracks': [
            ('Blade Runner Blues', 'Vangelis', '8:54'),
            ('On the Nature of Daylight', 'Max Richter, Louisa Fuller, Natalia Bonner, John Metcalfe, Philip Sheppard, Chris Worsey', '6:12'),
            ('A Meaningful Moment Through a Meaning(less) Process', 'Stars Of The Lid', '4:33'),
            ('energy flow', 'Ryuichi Sakamoto', '4:33'),
            ('Prizewinning', 'Julianna Barwick', '6:43'),
            ('Kids Will Be Skeletons', 'Mogwai', '5:27'),
            ('saman', 'Ólafur Arnalds', '2:12'),
            ('Mysterium', 'Hammock', '7:12'),
            ('Pop 1', 'GAS', '5:12'),
            ('#3', 'Aphex Twin', '7:44'),
            ('Sea, Swallow Me - 2024 Remaster', 'Cocteau Twins, Harold Budd', '3:10'),
            ('Steep Hills of Vicodin Tears', 'A Winged Victory for the Sullen, Adam Wiltzie, Dustin O\'Halloran', '4:27'),
            ('Flight from the City', 'Jóhann Jóhannsson, Yuki Numata Resnick, Tarn Travers, Ben Russell, Clarice Jensen', '6:31'),
        ]
    },
    {
        'day': 'Tuesday',
        'time': '10:30am – Noon',
        'name': 'The Strategy',
        'tracks': [
            ('Hopopono', 'GoGo Penguin', '3:57'),
            ('Ruins', 'Portico Quartet', '5:34'),
            ('A Tender History In Rust', 'Do Make Say Think', '5:07'),
            ('Kandaiki', 'Mammal Hands', '5:16'),
            ('The Awakening Of A Woman - Burnout', 'The Cinematic Orchestra', '10:20'),
            ('Black Water', 'Apparat', '4:54'),
            ('The Birds', 'Telefon Tel Aviv', '6:38'),
            ('Dayvan Cowboy', 'Boards of Canada', '5:00'),
            ('York', 'Christian Löffler', '7:57'),
            ('The Mighty Rio Grande', 'This Will Destroy You', '11:17'),
            ('Switch', 'Nils Petter Molvær', '6:54'),
            ('Flim', 'The Bad Plus', '4:05'),
            ('Toccata', 'Jaga Jazzist', '9:11'),
            ('Recovery', 'Rival Consoles', '4:50'),
        ]
    },
    {
        'day': 'Tuesday',
        'time': 'Noon – 2:00pm',
        'name': 'The Global Bazaar',
        'tracks': [
            ('This Must Be the Place (Naive Melody) - 2005 Remaster', 'Talking Heads', '4:56'),
            ('Atomic Bomb', 'William Onyeabor', '7:60'),
            ("Busy Earnin'", 'Jungle', '3:02'),
            ('Taj Mahal', 'Jorge Ben Jor', '3:07'),
            ('Disparate Youth', 'Santigold', '4:44'),
            ('Amidinine', 'Bombino', '4:29'),
            ('Stylo (feat. Mos Def and Bobby Womack)', 'Gorillaz, Bobby Womack, Mos Def', '4:31'),
            ('Die Young', 'Sylvan Esso', '3:31'),
            ('Paper Planes', 'M.I.A.', '3:25'),
            ("Que' Onda Guero", 'Beck', '3:29'),
            ('Kamelemba', 'Oumou Sangaré', '4:14'),
            ('Daft Punk Is Playing at My House', 'LCD Soundsystem', '5:15'),
            ('Crazy', 'Gnarls Barkley, CeeLo Green, Danger Mouse', '3:02'),
            ('Give Me a Reason', 'Ibibio Sound Machine', '4:18'),
            ("Apollo's Mood", 'The Olympians', '4:31'),
            ('Taurus - Mixed', 'Glass Beams', '2:14'),
            ('Tezeta', 'Mulatu Astatke', '6:09'),
            ('Che Che Cole', 'Antibalas', '4:08'),
            ('Cissy Strut', 'The Meters', '3:07'),
            ('Mambo Rapidito', 'Orquesta Akokán', '3:19'),
            ('Cumbia Sobre El Mar', 'Quantic, Flowering Inferno', '6:17'),
            ('Que Sera', 'Wax Tailor', '2:44'),
            ('Hit That Jive', 'Gramatik', '3:23'),
            ('T.I.B.W.F.', 'The Budos Band', '2:41'),
            ('Suzuki', 'Tosca', '6:04'),
            ('aruarian dance', 'Nujabes', '4:10'),
            ('Do The Astral Plane', 'Flying Lotus', '3:58'),
        ]
    },
    {
        'day': 'Tuesday',
        'time': '2:00 – 5:00pm',
        'name': 'The Collaboratory',
        'tracks': [
            ('Computer Love', 'Kraftwerk', '6:33'),
            ('Vitamin C - 2004 Remastered Version', 'CAN', '3:34'),
            ('Ankle Injuries', 'Fujiya & Miyagi', '5:05'),
            ('Parasol', 'The Sea and Cake', '5:30'),
            ('Tunnel', 'Minami Deutsch', '5:47'),
            ('Pendulum', 'Broadcast', '4:21'),
            ('Wulfstan II', 'Beak>', '7:13'),
            ('A Single Ray of Light on an Otherwise Cloudy Day', 'Trans Am', '1:30'),
            ('From the Outside', 'Camera', '4:39'),
            ('Drive Towards The Smoke', 'Ui', '5:07'),
            ('hi-hats bring the hiss', 'Cavern of Anti-Matter', '9:06'),
            ('Fort Greene Park', 'Battles', '5:45'),
            ('Spider Wolf', 'Polyrhythmics', '3:11'),
            ('Dove', 'Cymande', '10:55'),
            ('Supermoon', 'Ikebe Shakedown', '3:27'),
            ('Comencemos (Let\'s Start)', 'Jungle Fire', '2:33'),
            ('Nyx', 'Karl Hector & The Malcouns', '3:53'),
            ('Mista President (Remastered)', 'The Souljazz Orchestra', '6:37'),
            ('Kiss the Sky', 'Shawn Lee\'s Ping Pong Orchestra', '3:39'),
            ('Soulful Strut', 'Young-Holt Unlimited', '3:01'),
            ('Pass The Peas', 'The J.B.\'s', '3:32'),
            ('Phyllis', 'Lettuce', '6:50'),
            ('Green Onions', 'Booker T. & the M.G.\'s', '2:56'),
            ('Voyager', 'Daft Punk', '3:48'),
            ('Star Guitar', 'The Chemical Brothers', '6:27'),
            ('Cerulean', 'Simian Mobile Disco', '6:48'),
            ('Holding On', 'Classixx', '6:20'),
            ('Hearts On Fire', 'Cut Copy', '4:55'),
            ('Hold On', 'Holy Ghost!', '5:57'),
            ('Brokendate', 'Com Truise', '5:08'),
            ('Roadgame', 'Kavinsky', '3:44'),
            ('Resonance', 'Home', '3:33'),
            ('HALCYON + ON + ON', 'Orbital', '9:27'),
            ('At the River', 'Groove Armada', '6:34'),
            ('Space Walk', 'Lemon Jelly', '7:03'),
            ('Jumbo', 'Underworld', '6:58'),
            ('Sure Thing', 'St Germain', '6:20'),
            ('Lebanese Blonde', 'Thievery Corporation', '4:49'),
            ('Honey', 'Tosca', '5:57'),
            ('Tacoma Black Party - Live', 'Delvon Lamarr Organ Trio', '4:14'),
            ('Soul Sauce', 'Cal Tjader', '2:27'),
            ('Orchids', 'Monster Rally', '2:57'),
            ('Superhero', 'Kiefer', '2:46'),
            ('Velodrome', 'Surprise Chef', '3:14'),
            ('The Link Is About to Die', 'Los Bitchos', '3:48'),
            ('Everybody Loves The Sunshine', 'Roy Ayers Ubiquity', '3:60'),
            ('"T" Plays It Cool', 'Marvin Gaye', '4:27'),
            ('Nightrider', 'Tom Misch, Yussef Dayes, Freddie Gibbs', '5:01'),
            ('Desafinado', 'Stan Getz, Charlie Byrd', '5:49'),
            ('Time Moves Slow', 'BADBADNOTGOOD, Samuel T. Herring', '4:34'),
        ]
    },
    # WEDNESDAY
    {
        'day': 'Wednesday',
        'time': '9:00 – 10:30am',
        'name': 'The Blueprint',
        'tracks': [
            ('Electric Counterpoint: III. Fast', 'Steve Reich, Mats Bergström', '4:29'),
            ('tremolo+delay', 'toe', '3:03'),
            ('falkor', 'Covet', '7:37'),
            ('Finger', 'Elephant Gym', '5:03'),
            ('Early in the Park', 'Hauschka', '3:04'),
            ('Nix', 'Dawn of Midi', '3:39'),
            ('Slightly Drifting', 'The Mercury Program', '6:24'),
            ('Stay Home', 'American Football', '8:10'),
            ('Elk', 'TTNG', '3:51'),
            ('Gameshow Buzzer', 'Ghosts and Vodka', '4:37'),
            ('Prepare Your Coffin', 'Tortoise', '3:38'),
            ('The Yabba', 'Battles', '6:49'),
            ('In the Absence of Strong Evidence to the Contrary, One May Step Out of the Way of the Charging Bull', 'Don Caballero', '4:36'),
            ('Fingerbib (Arr. J. Newman)', 'Aphex Twin, Alarm Will Sound, Allan Pierson', '3:49'),
            ('Music For A Found Harmonium - 2008 Digital Remaster', 'Penguin Cafe Orchestra', '3:40'),
            ('The Riverbed', 'Owen Pallett', '3:44'),
            ("Logan's Loop", 'Andrew Bird', '1:09'),
            ('Sweden', 'C418', '3:36'),
            ('Fanshawe', 'El Ten Eleven', '5:12'),
            ('Penelope', 'Pinback', '4:47'),
            ('Cramm', 'Three Trapped Tigers', '4:59'),
            ('Glassworks: I. Opening', 'Philip Glass, Philip Glass Ensemble, Michael Riesman', '6:25'),
        ]
    },
    {
        'day': 'Wednesday',
        'time': '10:30am – Noon',
        'name': 'The Scaffold',
        'tracks': [
            ('Fantas Morbida - Kara-Lis Coverdale', 'Caterina Barbieri, Kara-Lis Coverdale', '3:08'),
            ('Perdonare', 'Alessandro Cortini', '4:53'),
            ('Arthur', 'Kelly Lee Owens', '4:05'),
            ('Iambic 9 Poetry - Remastered', 'Squarepusher', '6:56'),
            ('Alberto Balsalm', 'Aphex Twin', '5:11'),
            ('Roygbiv', 'Boards of Canada', '2:29'),
            ('Do Matter', 'Plaid', '3:41'),
            ('A New Error', 'Moderat', '6:07'),
            ('Open Eye Signal - Remaster 2023', 'Jon Hopkins', '7:49'),
            ('Odyssey', 'Rival Consoles', '4:42'),
            ('Arcadia', 'Apparat', '5:10'),
            ('Split Stones', 'Lymbyc Systym', '5:59'),
            ('Radio Protector', '65daysofstatic', '5:26'),
            ('Tom Tom', 'Holy Fuck', '3:48'),
            ('Niobe', 'Caribou', '8:51'),
            ('Ratio - Edit', 'Floating Points', '3:21'),
            ('Belfast', 'Orbital', '8:11'),
        ]
    },
    {
        'day': 'Wednesday',
        'time': 'Noon – 2:00pm',
        'name': 'The Design Studio',
        'tracks': [
            ('New Music Machine', 'Cornelius', '3:53'),
            ('Again & Again', 'the bird and the bee', '2:46'),
            ('ベイビィ・ポータブル・ロック', 'ピチカート・ファイヴ', '4:03'),
            ('二十歳の恋', 'Lamp', '3:13'),
            ('Too Young', 'Phoenix', '3:18'),
            ('Over And Over', 'Hot Chip', '5:48'),
            ('Birth In Reverse', 'St. Vincent', '3:16'),
            ('Water Fountain', 'Tune-Yards', '3:03'),
            ('1612', 'Vulfpeck', '3:20'),
            ('Not Enough', 'Benny Sings', '2:59'),
            ('Mais Que Nada', 'Sergio Mendes & Brasil \'66', '2:39'),
            ('Who', 'David Byrne, St. Vincent', '3:50'),
            ('Ping Pong', 'Stereolab', '3:02'),
            ('Kemosabe', 'Everything Everything', '3:44'),
            ('Iron Man', 'The Bad Plus', '6:02'),
            ('Summer Samba (So Nice)', 'Walter Wanderley', '3:07'),
            ('Steppin\' Out - Costes reedit', 'FPM, Hôtel Costes', '5:17'),
            ('Soul Bossa Nova', 'Quincy Jones', '2:47'),
            ('Giddy And Gay', 'The High Llamas', '4:56'),
            ('Shinrinyoku', 'Sven Wunder', '2:34'),
            ('Ginger on the Wind', 'Monster Rally', '2:09'),
            ('Organ Donor', 'DJ Shadow', '1:57'),
            ('A Beautiful Mine', 'RJD2', '5:29'),
            ('Marriage', 'Gold Panda', '4:41'),
            ("Arthur's Birds", 'Teebs', '5:17'),
            ('Grammar', 'Floating Points', '7:42'),
        ]
    },
    {
        'day': 'Wednesday',
        'time': '2:00 – 5:00pm',
        'name': 'The Workshop',
        'tracks': [
            ('Tokyo', 'The Books', '3:43'),
            ('Bullets', 'Tunng', '5:59'),
            ('Green Green Grass Of Tunnel', 'múm', '4:51'),
            ('Un Día', 'Juana Molina', '5:35'),
            ('(This Is) The Dream Of Evan And Chan - Remastered', 'Dntel', '5:45'),
            ('Pilot', 'The Notwist', '4:29'),
            ("Grey's Anatomy", 'Movie Sounds Unlimited', '4:25'),
            ('Faking The Books', 'Lali Puna', '4:00'),
            ('Manchester', 'Kishi Bashi', '4:06'),
            ('Rainbow Flag', 'Matmos', '3:52'),
            ('In Ruins (Baths Remix)', 'Fol Chen, Baths', '4:03'),
            ('Lay in a Shimmer', 'Pantha Du Prince', '6:38'),
            ('Adler - Heimiche Gefilde Remix', 'Dominik Eulberg', '5:50'),
            ('Alpe Lusia', 'Stimming', '3:12'),
            ('Roots', 'Romare', '7:54'),
            ('Carbonated', 'Mount Kimbie', '4:19'),
            ('El Bandido', 'Nicolas Jaar', '6:37'),
            ('Elixir', 'Tourist', '5:07'),
            ("Talk to Me You'll Understand", 'Ross from Friends', '6:57'),
            ('Movements (Chapter III)', 'Leon Vynehall', '3:52'),
            ('Pick Up', 'DJ Koze', '6:38'),
            ('Hello', 'Axel Boman', '8:39'),
            ('Kuj Yato', 'Clap! Clap!', '3:34'),
            ('Sailing the Solar Flares', 'Dirtwire', '4:15'),
            ('Home', 'Moontricks', '4:46'),
            ('The Wheel', 'SOHN', '3:53'),
            ('Pharaohs', 'SBTRKT, Roses Gabor', '3:38'),
            ('Aquarium', 'Nosaj Thing', '3:04'),
            ('Never Mess With Sunday', 'Yppah', '3:16'),
            ('Ritual Union', 'Little Dragon', '3:30'),
            ('Polish Girl', 'Neon Indian', '4:22'),
            ('Rose Quartz', 'Toro y Moi', '4:13'),
            ('Boys Latin', 'Panda Bear', '4:12'),
            ('True Thrush', 'Dan Deacon', '4:45'),
        ]
    },
    # THURSDAY
    {
        'day': 'Thursday',
        'time': '9:00 – 10:30am',
        'name': 'The Prologue',
        'tracks': [
            ("Comptine d'un autre été, l'après-midi", 'Yann Tiersen', '2:21'),
            ('We Move Lightly', 'Dustin O\'Halloran', '3:10'),
            ('The Curse', 'Agnes Obel', '5:53'),
            ('Eyes Closed And Traveling', 'Peter Broderick', '3:40'),
            ('Water from the Same Source', 'Christian Erik Frederickson, Jason Bingham Noble, Rachel Grimes, Rachel\'s', '6:18'),
            ('Pockets of Light', 'Lubomyr Melnyk', '19:00'),
            ('Sleeping Lotus', 'Joep Beving', '2:32'),
            ('Brown Creek', 'Goldmund', '4:25'),
            ('Unexpected Travel', 'Fabrizio Paterlini', '3:44'),
            ('By Night', 'Sophie Hutchings', '5:29'),
            ('Lost River Blues I', 'Esmerine', '7:26'),
        ]
    },
    {
        'day': 'Thursday',
        'time': '10:30am – Noon',
        'name': 'The Rising Action',
        'tracks': [
            ('Lux Aeterna', 'Clint Mansell, Kronos Quartet', '3:54'),
            ('Dance For Me Wallis', 'Abel Korzeniowski', '3:08'),
            ('Bloodflow', 'Grandbrothers', '5:58'),
            ('The righteous wrath of an honorable man', 'Colin Stetson', '2:28'),
            ('Hero Brother', 'Sarah Neufeld', '4:49'),
            ('This Is How We Walk On The Moon', 'Arthur Russell', '4:43'),
            ("Maxim's I", 'Julia Holter', '6:07'),
            ('Pencil Stick', 'Clogs', '6:08'),
            ('As Ballad', 'Lambert', '4:54'),
            ('Motion Picture Soundtrack', 'Vitamin String Quartet', '2:42'),
            ('Recomposed By Max Richter: Vivaldi, The Four Seasons: Spring 1 - 2012', 'Max Richter, Daniel Hope, Konzerthaus Kammerorchester Berlin, Andre de Ridder', '2:35'),
        ]
    },
    {
        'day': 'Thursday',
        'time': 'Noon – 2:00pm',
        'name': 'The Salon',
        'tracks': [
            ('Le temps de l\'amour - Stereo Mix', 'Françoise Hardy', '2:25'),
            ('Bonnie And Clyde', 'Brigitte Bardot, Serge Gainsbourg', '4:16'),
            ('The Songs That We Sing', 'Charlotte Gainsbourg', '2:57'),
            ('Care of Cell 44 - Mono Remastered', 'The Zombies', '3:16'),
            ('National Express', 'The Divine Comedy', '5:06'),
            ('The Old Man\'s Back Again (Dedicated To The Neo-Stalinist Regime)', 'Scott Walker', '3:41'),
            ('Alone Again Or - 2015 Remaster', 'Love', '3:17'),
            ('I Follow You', 'Melody\'s Echo Chamber', '3:34'),
            ('Où va le monde', 'La Femme', '5:38'),
            ("Cybele's Reverie", 'Stereolab', '4:43'),
            ('Di doo dah', 'Jane Birkin', '3:34'),
            ('French Navy', 'Camera Obscura', '3:19'),
            ('The Village Green Preservation Society', 'The Kinks', '2:53'),
            ('Di-gue-ding-ding', 'Michel Legrand', '2:41'),
            ('Dernier domicile connu - Bande originale du film "Dernier domicile connu"', 'François de Roubaix', '3:56'),
            ('Le bracelet', 'Alain Goraguer', '1:28'),
            ('Coffee Cold', 'Galt MacDermot', '3:26'),
            ('Danube Incident', 'Lalo Schifrin', '1:58'),
            ('Holy Thursday', 'David Axelrod', '5:31'),
            ('Playground Love - Vibraphone Version', 'Air', '3:49'),
            ('La ritournelle', 'Sébastien Tellier', '7:34'),
        ]
    },
    {
        'day': 'Thursday',
        'time': '2:00 – 5:00pm',
        'name': 'The Edit Suite',
        'tracks': [
            ('Protection', 'Massive Attack, Tracey Thorn', '7:52'),
            ('Sour Times', 'Portishead', '4:12'),
            ('Gritty Shaker', 'David Holmes', '6:40'),
            ('6 Underground - Nellee Hoopers Edit', 'Sneaker Pimps', '3:55'),
            ('Seize The Day', 'Wax Tailor, Charlotte Savary', '2:42'),
            ('Nights Introlude', 'Nightmares On Wax', '4:40'),
            ("Just Jammin'", 'Gramatik', '6:30'),
            ('The Music Scene', 'Blockhead', '4:50'),
            ("Start Shootin'", 'Little People', '3:37'),
            ('Cold Water Music', 'Aim', '5:44'),
            ('Smoke & Mirrors', 'RJD2', '4:26'),
            ('Basin Street Blues', 'Kid Koala', '4:47'),
            ('The Truth', 'Handsome Boy Modeling School, Dan The Automator, Prince Paul, Róisín Murphy, J-Live', '5:37'),
            ('Blue Pedro', 'Bullion', '5:13'),
            ('One Word Extinguisher', 'Prefuse 73', '4:04'),
            ('Dieu Reconnaitra Les Siens', 'DJ Cam', '6:04'),
            ('Midnight In A Perfect World', 'DJ Shadow', '4:58'),
            ('Flite', 'The Cinematic Orchestra', '6:36'),
            ('Antiphon', 'Hidden Orchestra', '6:08'),
            ('High', 'Skalpel', '4:25'),
            ('Hot Flush - Sabres Of Paradise Remix', 'Red Snapper, The Sabres Of Paradise', '8:05'),
            ('Bridge', 'Amon Tobin', '5:56'),
            ('High Noon', 'Kruder & Dorfmeister', '6:26'),
            ('Night over Manaus', 'Boozoo Bajou', '6:19'),
            ('Chocolate Elvis', 'Tosca', '5:02'),
            ('2 Wicky', 'Hooverphonic', '4:44'),
            ('Gorecki', 'Lamb', '6:30'),
            ('Underwater Love', 'Smoke City', '6:46'),
            ('Tape Loop', 'Morcheeba', '4:23'),
            ('Poundstretcher', '9 Lazy 9', '7:39'),
            ('Purrfect', 'Funki Porcini', '4:51'),
            ('The Blend', 'The Herbaliser, What What', '3:41'),
            ('Lonely Soul - In Tune and On Time', 'UNKLE, Richard Ashcroft', '2:54'),
            ('Hell Is Round The Corner', 'Tricky, Martina Topley-Bird', '3:47'),
            ('Theme of \'\'Rome\'\'', 'Danger Mouse, Daniele Luppi', '2:21'),
            ('Turn Down the Sound', 'Adrian Younge, Loren Oden', '3:13'),
            ('The Traitor', 'Menahan Street Band', '2:42'),
            ('Duel Of The Iron Mics', 'El Michels Affair', '3:02'),
            ('Frontier Psychiatrist', 'The Avalanches', '4:48'),
            ('Double Bass', 'Gorillaz', '4:47'),
            ('Book of the Month - Instrumental', 'Lovage, Nathaniel Merriweather', '4:38'),
            ('Give It Away', 'Zero 7', '5:17'),
            ('Inside My Mind (Blue Skies)', 'Groove Armada', '8:00'),
            ('All That We Perceive', 'Thievery Corporation', '3:46'),
            ('Music Is Math', 'Boards of Canada', '5:21'),
            ('Porcelain', 'Moby', '4:01'),
            ('Alone in Kyoto', 'Air', '4:51'),
            ('You Wish', 'Nightmares On Wax', '3:29'),
        ]
    },
    # FRIDAY
    {
        'day': 'Friday',
        'time': '9:00 – 10:30am',
        'name': 'The Innovation Lab',
        'tracks': [
            ('Kitchen', 'The Soft Pink Truth', '3:05'),
            ('Huron River Drive', 'Shigeto', '2:40'),
            ('Without You', 'Lapalux, Kerry Leatham', '5:26'),
            ('Feels', 'Giraffage', '3:11'),
            ('About You', 'xxyyxx', '4:08'),
            ('Realla', 'TOKiMONSTA, Anderson .Paak', '3:30'),
            ('Places', 'Shlohmo', '5:02'),
            ('Aminals', 'Baths', '3:18'),
            ('Me dê Amor (Feat. Gaiola das Popozudas)', 'Sango', '3:18'),
            ('LONG DISTANCE', 'Sam Gellaitry', '3:39'),
            ('Lotus Eater', 'Mura Masa', '2:26'),
            ('On Your Side', 'Opiuo, Russ Liquid', '4:08'),
        ]
    },
    {
        'day': 'Friday',
        'time': '10:30am – Noon',
        'name': 'The Flow State',
        'tracks': [
            ('U', 'DJ Seinfeld', '6:08'),
            ('Passionfruit', 'Yaeji', '4:35'),
            ('Winona', 'DJ BORING', '8:31'),
            ('Decompression', 'Harrison BDP', '7:56'),
            ('Saw You for the First Time', 'Laurence Guy', '6:45'),
            ('Ahead Of Time', 'Baltra, 박혜진 Park Hye Jin', '6:59'),
            ('Healing', 'COMPUTER DATA', '6:15'),
            ('U, Me and Madonna', '1-800 GIRLS', '4:10'),
            ('Midnight in Peckham', 'Chaos In The CBD, Isaac Aesili', '7:01'),
            ('Ivoire', 'Folamour', '8:16'),
            ('Pantalón', 'Kornél Kovács', '4:21'),
            ('Gosh', 'Jamie xx, MC Moose', '4:51'),
        ]
    },
    {
        'day': 'Friday',
        'time': 'Noon – 2:00pm',
        'name': 'The Rooftop',
        'tracks': [
            ('Nana', 'Acid Pauli', '9:22'),
            ('Hologram', 'Bedouin', '8:09'),
            ('Andromeda', 'Be Svendsen', '6:46'),
            ('Aragatz', 'Viken Arman', '7:08'),
            ('Days Without You', 'Satori, Miou Amadée', '6:41'),
            ('Drinkee (Vintage Culture & John Summit Remix)', 'Sofi Tukker, Vintage Culture, John Summit', '3:25'),
            ('Sirens', 'Monolink', '3:37'),
            ('More', 'Jan Blomqvist, Elena Pitoulis', '3:37'),
            ('Tearing Me Up', 'Bob Moses', '7:50'),
            ('Heads Above', 'WhoMadeWho', '4:21'),
            ('Innerbloom', 'RÜFÜS DU SOL', '9:38'),
            ('Je Vulesse', 'Nu Genea', '4:48'),
            ('Homage', 'Mild High Club', '2:57'),
            ('Loretta', 'Ginger Root', '3:10'),
            ('Show Me How', 'Men I Trust', '3:35'),
            ('Sink into the Floor', 'Feng Suave', '4:41'),
            ('Cariño', 'The Marías', '4:19'),
            ('Locket', 'Crumb', '5:18'),
            ('Crave You', 'Flight Facilities, Giselle', '3:55'),
            ('Baby I\'m Yours - Instrumental', 'Breakbot, Irfane', '3:36'),
            ('Sodade', 'Cesária Evora', '4:54'),
            ('El Cuarto de Tula', 'Buena Vista Social Club', '7:25'),
            ('Ai Du - with Ry Cooder', 'Ali Farka Touré, Ry Cooder', '7:10'),
            ('Tamacún', 'Rodrigo y Gabriela', '3:26'),
            ('Sympathique (Je ne veux pas travailler)', 'Pink Martini', '2:48'),
            ('Seya', 'Oumou Sangaré', '4:13'),
            ('Raoui', 'Souad Massi', '3:47'),
            ('Una Pastora', 'Yasmin Levy', '2:05'),
            ('Un Amor', 'Gipsy Kings', '3:37'),
            ('Entre Dos Aguas', 'Paco de Lucía', '6:02'),
            ('Cantelowes', 'Toumani Diabaté', '6:58'),
            ('Nterini', 'Fatoumata Diawara', '3:44'),
            ('Aké', 'Blick Bassy', '3:33'),
            ('Wiyathul', 'Gurrumul', '5:53'),
            ('Cucurrucucú Paloma', 'Lila Downs', '4:50'),
            ('Soledad y el Mar (feat. Los Macorinos)', 'Natalia Lafourcade, Los Macorinos', '3:35'),
            ('Ave Que Emigra', 'Gaby Moreno', '4:20'),
            ('Bruca Maniguá', 'Ibrahim Ferrer', '4:44'),
            ('Tres Notas para Decir Te Quiero', 'Vicente Amigo', '4:49'),
            ('Chamber Music', 'Ballaké Sissoko, Vincent Segal', '5:31'),
            ('Utrus Horas', 'Orchestra Baobab', '8:43'),
        ]
    },
    {
        'day': 'Friday',
        'time': '2:00 – 5:00pm',
        'name': 'The Launch Party',
        'tracks': [
            ('Nana', 'Acid Pauli', '9:22'),
            ('Hologram', 'Bedouin', '8:09'),
            ('Andromeda', 'Be Svendsen', '6:46'),
            ('Aragatz', 'Viken Arman', '7:08'),
            ('Days Without You', 'Satori, Miou Amadée', '6:41'),
            ('Drinkee (Vintage Culture & John Summit Remix)', 'Sofi Tukker, Vintage Culture, John Summit', '3:25'),
            ('Sirens', 'Monolink', '3:37'),
            ('More', 'Jan Blomqvist, Elena Pitoulis', '3:37'),
            ('Tearing Me Up', 'Bob Moses', '7:50'),
            ('Heads Above', 'WhoMadeWho', '4:21'),
            ('Innerbloom', 'RÜFÜS DU SOL', '9:38'),
            ('Sit Next to Me', 'Foster The People', '4:03'),
            ('What You Know', 'Two Door Cinema Club', '3:11'),
            ('Electric Feel', 'MGMT', '3:50'),
            ('Golden Light', 'STRFKR', '4:43'),
            ('Fall In Love', 'Phantogram', '3:43'),
            ('Gooey', 'Glass Animals', '4:49'),
            ('Breezeblocks', 'alt-J', '3:47'),
            ('Wide Eyes', 'Local Natives', '4:26'),
            ('O.N.E.', 'Yeasayer', '5:24'),
            ('Intro', 'Disclosure', '1:01'),
            ('Sleepless feat. Jezzabell Doran', 'Flume, Jezzabell Doran', '3:29'),
            ('Sun Models', 'ODESZA, Madelyn Grant', '2:40'),
            ('Breathing', 'Ben Böhmer, Nils Hoffmann, Malou', '3:43'),
            ('Because You Move Me', 'Tinlicker, Helsloot', '3:16'),
            ('Intergalactic Plastic - Edit', 'Luttrell', '4:22'),
            ('Marisa', 'YOTTO', '4:33'),
            ('Flow', 'Crooked Colours', '4:50'),
            ('Old Friend', 'Elderbrook', '3:20'),
            ('Cumbia del Olvido', 'Nicola Cruz', '3:36'),
            ('Mañana Tepotzlan', 'El Búho', '4:00'),
            ('Sueno en Paraguay', 'Chancha Via Circuito', '3:53'),
            ('Something About You', 'Hayden James', '3:45'),
            ('Pizza Guy', 'Touch Sensitive', '5:49'),
            ('Holidays', 'Miami Horror, Alan Palomo', '4:28'),
            ('Fifteen', 'Goldroom, Chela et Cetera', '4:60'),
            ('Let Go', 'RAC, Kele, MNDR', '4:40'),
            ('Holding On', 'Classixx', '6:20'),
            ('Calling Out', 'Penguin Prison', '3:59'),
            ('Control', 'Gigamesh, Caroline Smith', '4:25'),
            ('Sunlight (feat. Years and Years)', 'The Magician, Olly Alexander (Years & Years)', '3:13'),
            ('Coma Cat', 'Tensnake', '6:56'),
            ('Ocean Drive', 'Duke Dumont', '3:26'),
            ('Young Blood', 'The Naked And Famous', '4:07'),
            ('Take a Walk', 'Passion Pit', '4:25'),
            ('Genghis Khan', 'Miike Snow', '3:32'),
            ('Closer', 'Lemaitre, Jennie A.', '4:31'),
            ('Shooting Stars', 'Bag Raiders', '3:47'),
        ]
    },
    # SATURDAY
    {
        'day': 'Saturday',
        'time': '10:00am – Noon',
        'name': 'The Dusty Porch',
        'tracks': [
            ('Santa Maria De Feira', 'Devendra Banhart', '4:35'),
            ('Postcards from Italy', 'Beirut', '4:17'),
            ('40 Day Dream', 'Edward Sharpe & The Magnetic Zeros', '3:54'),
            ('Beautiful Strangers', 'Kevin Morby', '6:16'),
            ('The Rifle', 'Alela Diane', '2:43'),
            ('More Of This', 'Vetiver', '4:00'),
            ('Humbug Mountain Song', 'Fruit Bats', '3:04'),
            ('Beggar in the Morning', 'The Barr Brothers', '5:55'),
            ("Where'd All the Time Go?", 'Dr. Dog', '3:55'),
            ('Black Water', 'Timber Timbre', '5:60'),
            ('Astral Plane', 'Valerie June', '3:39'),
            ('Home Again', 'Michael Kiwanuka', '3:32'),
            ('One of These Days', 'Bedouine', '2:59'),
            ("Pa'lante", 'Hurray For The Riff Raff', '5:53'),
            ('I Am The Changer', 'Cotton Jones', '6:35'),
            ('Moving to the Left', 'Woods', '5:23'),
            ('Be Good or Be Gone', 'Fionn Regan', '3:20'),
            ('Ghosts', 'Laura Marling', '2:60'),
            ('The Wrote & The Writ', 'Johnny Flynn', '4:07'),
            ('Moonshine Freeze', 'This Is The Kit', '3:42'),
            ('Home to You', 'Cate Le Bon', '5:27'),
            ('The Barrel', 'Aldous Harding', '4:59'),
            ('The Magician', 'Andy Shauf', '3:52'),
            ('Oom Sha La La', 'Haley Heynderickx', '2:57'),
            ('Roll The Bones', 'Shakey Graves', '4:04'),
            ('The Way We Move', 'Langhorne Slim, The Law', '2:49'),
            ('3 Rounds and a Sound', 'Blind Pilot', '4:27'),
            ('Big Black Car', 'Gregory Alan Isakov', '3:37'),
            ('The Gardener', 'The Tallest Man On Earth', '3:57'),
            ('Emmylou', 'First Aid Kit', '4:18'),
            ('Chinese Translation', 'M. Ward', '3:59'),
            ('Boy With a Coin', 'Iron & Wine', '4:06'),
        ]
    },
    {
        'day': 'Saturday',
        'time': 'Noon – 2:00pm',
        'name': 'The Global Bazaar',
        'tracks': [
            ('Sodade', 'Cesária Evora', '4:54'),
            ('El Cuarto de Tula', 'Buena Vista Social Club', '7:25'),
            ('Ai Du - with Ry Cooder', 'Ali Farka Touré, Ry Cooder', '7:10'),
            ('Tamacún', 'Rodrigo y Gabriela', '3:26'),
            ('Sympathique (Je ne veux pas travailler)', 'Pink Martini', '2:48'),
            ('Seya', 'Oumou Sangaré', '4:13'),
            ('Raoui', 'Souad Massi', '3:47'),
            ('Una Pastora', 'Yasmin Levy', '2:05'),
            ('Un Amor', 'Gipsy Kings', '3:37'),
            ('Entre Dos Aguas', 'Paco de Lucía', '6:02'),
            ('Cantelowes', 'Toumani Diabaté', '6:58'),
            ('Nterini', 'Fatoumata Diawara', '3:44'),
            ('Aké', 'Blick Bassy', '3:33'),
            ('Wiyathul', 'Gurrumul', '5:53'),
            ('Cucurrucucú Paloma', 'Lila Downs', '4:50'),
            ('Soledad y el Mar (feat. Los Macorinos)', 'Natalia Lafourcade, Los Macorinos', '3:35'),
            ('Ave Que Emigra', 'Gaby Moreno', '4:20'),
            ('Bruca Maniguá', 'Ibrahim Ferrer', '4:44'),
            ('Tres Notas para Decir Te Quiero', 'Vicente Amigo', '4:49'),
            ('Chamber Music', 'Ballaké Sissoko, Vincent Segal', '5:31'),
            ('Utrus Horas', 'Orchestra Baobab', '8:43'),
        ]
    },
    {
        'day': 'Saturday',
        'time': '2:00 – 5:00pm',
        'name': 'The Crossroads',
        'tracks': [
            ('Me Gustas Tu', 'Manu Chao', '3:60'),
            ('Hello', 'The Cat Empire', '3:44'),
            ('Wonderlust King', 'Gogol Bordello', '3:58'),
            ('Asfalt Tango', 'Fanfare Ciocarlia', '6:13'),
            ('War', 'Hypnotic Brass Ensemble', '2:54'),
            ('Sexual Healing', 'Hot 8 Brass Band', '5:01'),
            ('Bad Man Lighter (B.M.L.)', 'Seun Kuti, Egypt 80', '7:48'),
            ('Secret Agent - 2022 Remaster', 'Tony Allen', '5:18'),
            ('Bulgarian Chicks (feat. Vlada Tomova & Kristin Espeland)', 'Balkan Beat Box, Vlada Tomova, Kristin Espeland', '5:53'),
            ('Disko Partizani', 'Shantel', '4:53'),
            ('Musonsu', 'Jupiter & Okwess', '3:37'),
            ('Soubour', 'Songhoy Blues', '3:32'),
            ('Tahabort', 'Imarhan', '3:31'),
            ('Imuhar', 'Bombino', '3:49'),
            ('Crystal Frontier - Widescreen Version', 'Calexico', '3:59'),
            ('Je pense à toi', 'Amadou & Mariam', '5:17'),
            ('Fafa', 'Vieux Farka Touré', '5:03'),
            ('Brooklyn', 'Youngblood Brass Band', '6:52'),
            ('Gospel', 'MarchFourth', '5:43'),
            ('Si, Se Puede', 'Antibalas', '9:55'),
            ('Bongo Bong', 'Manu Chao', '2:38'),
        ]
    },
]


def main():
    output_file = 'master_playlist_index.csv'

    with open(output_file, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.writer(csvfile)

        # Write header
        writer.writerow(['Day', 'Time', 'Playlist Name', 'Song Name', 'Artist', 'Duration'])

        # Write all tracks
        for schedule_block in schedule_data:
            day = schedule_block['day']
            time = schedule_block['time']
            name = schedule_block['name']

            for track in schedule_block['tracks']:
                song_name, artist, duration = track
                writer.writerow([day, time, name, song_name, artist, duration])

    print(f"Master playlist index created: {output_file}")
    print(f"Total schedule blocks: {len(schedule_data)}")
    print(f"Total tracks: {sum(len(block['tracks']) for block in schedule_data)}")


if __name__ == '__main__':
    main()
